# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiserver:
  image:
    repository: ghcr.io/agntcy/dir-apiserver
    tag: v0.5.6
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regcred

  log_level: DEBUG

  metrics:
    enabled: false

  zot:
    extraVolumes:
      - name: zot-config-storage
        persistentVolumeClaim:
          claimName: "agntcy-dir-zot-config"

  config:
    routing:
      refresh_interval: "1s"

    publication:
      scheduler_interval: "1s"
