#!/usr/bin/env bash
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
#
# Writes compose/dns/Corefile and compose/dns/csittest.zone for the host DNS helper.
# Cluster A ingress names resolve to the ingress-nginx LoadBalancer IP from
# cloud-provider-kind (.gen/ingress-a.env). Uses the file plugin for csit.test so
# explicit RRsets precede the wildcard without relying on the order plugin.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/compose/dns/Corefile"
ZONE_FILE="${ROOT}/compose/dns/csittest.zone"
ZONE="${CSIT_DNS_ZONE:-csit.test}"
ENV_FILE="${ROOT}/.gen/ingress-a.env"

if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${ENV_FILE}"
else
  echo "render-local-dns-corefile: WARN: ${ENV_FILE} missing — run task ingress:a:wait-lb-ip or set CSIT_INGRESS_IP_A (defaulting cluster A to 127.0.0.1)" >&2
fi

# Explicit override wins, then LB IP from discover script, then loopback (dev-only).
IP_A="${CSIT_INGRESS_IP_A:-${INGRESS_A_LB_IP:-127.0.0.1}}"
# KinD cluster B host port maps (9080/9443); no ingress on B.
IP_B="${CSIT_INGRESS_IP_B:-127.0.0.1}"
WILDCARD_IP="${CSIT_DNS_CATCHALL_IP:-${IP_B}}"
UPSTREAM="${CSIT_DNS_UPSTREAM:-1.1.1.1}"
umask 022
if [[ -d "${OUT}" ]]; then
  echo "render-local-dns-corefile: removing mistaken directory at ${OUT}" >&2
  rm -rf "${OUT}"
fi
mkdir -p "$(dirname "${OUT}")"

cat >"${ZONE_FILE}" <<ZEOF
\$ORIGIN ${ZONE}.
\$TTL 60
@   IN SOA localhost. none.invalid. (
            1       ; serial
            3600    ; refresh
            1800    ; retry
            604800  ; expire
            60 )    ; minimum
    IN NS localhost.

control.cluster-a    IN A ${IP_A}
control.nb.cluster-a IN A ${IP_A}
slim.cluster-a       IN A ${IP_A}
spire.cluster-a      IN A ${IP_A}
spire-bundle.cluster-a IN A ${IP_A}
slim.cluster-b       IN A ${IP_B}
*                    IN A ${WILDCARD_IP}
ZEOF

cat >"${OUT}" <<EOF
# Generated by render-local-dns-corefile.sh
# Zone db: csittest.zone (ingress VIP + wildcard for other *.${ZONE}).
${ZONE}:53 {
    errors
    log
    file /etc/coredns/csittest.zone
}

.:53 {
    errors
    log
    forward . ${UPSTREAM}
}
EOF
echo "Wrote ${OUT} and ${ZONE_FILE} (cluster A → ${IP_A})"
