topology:
    clients:
        "alice":
            # auth:
            #     spireJwt: true
            connectedTo:
                - "slim-1"
            image: ghcr.io/agntcy/slim/bindings-examples:latest          
            args: ["ff", "--local", "org/ns/alice", "--shared-secret","secret123"]  
            assertFor: "replies: hello from"                                        
        "bob":
            # auth:
            #     spireJwt: true
            connectedTo:
                - "slim-2"
            image: ghcr.io/agntcy/slim/bindings-examples:latest                      
            args: ["ff", "--message", "hello", "--iterations", "10", "--local", "org/ns/bob", "--remote", "org/ns/alice", "--shared-secret","secret123"]
            assertFor: "Sent message hello - 10/10"
    servers:
        "slim-0":
            spireMtls: false
            routes:                
                - "org/ns/bob > slim-2"  
                - "org/ns/alice > slim-1"              
        "slim-1":
            routes:                                
                - "org/ns/bob > slim-0"
        "slim-2":
            routes:                
                - "org/ns/alice > slim-0"                
