topology:
    clients:
        "alice":
            spireMtls: false
            connectedTo:
                - "cluster-b"
            image: ghcr.io/agntcy/slim/bindings-examples:local          
            args: 
              - slim-bindings-p2p
              - --local
              - org/ns/alice
              - --shared-secret
              - secret1234secret1234secret123412               
            #   - --spire-socket-path
            #   - unix:/tmp/spire-agent/public/api.sock
            #   - --spire-jwt-audience
            #   - slim-demo
            assertFor: "received: hello"                                        
        "bob":
            spireMtls: false
            connectedTo:
                - "cluster-a"
            image: ghcr.io/agntcy/slim/bindings-examples:local                      
            args:
              - slim-bindings-p2p
              - --local
              - org/ns/bob
              - --remote
              - org/ns/alice
              - --shared-secret
              - secret1234secret1234secret123412              
            #   - --spire-socket-path
            #   - unix:/tmp/spire-agent/public/api.sock
            #   - --spire-jwt-audience
            #   - slim-demo
              - --message
              - hello
              - --iterations
              - 10
            assertFor: "Sent message hello - 10/10"
    clusters:
        "cluster-a":
            spireMtls: false
            #deployAsDaemonSet: false
            replicaCount: 1             
        "cluster-b":
            spireMtls: false
            #deployAsDaemonSet: false
            replicaCount: 1