# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

includes:
  slim:
    taskfile: ./agntcy-slim/Taskfile.yml
    dir: ./agntcy-slim
    excludes: [default]

  directory:
    taskfile: ./agntcy-dir/Taskfile.yml
    dir: ./agntcy-dir
    excludes: [default]

  slim-vs-a2a:
    taskfile: ./slim-vs-a2a/Taskfile.yml
    dir: ./slim-vs-a2a
    excludes: [default]

  slim-vs-a2a-v2:
    taskfile: ./slim-vs-a2a-v2/Taskfile.yml
    dir: ./slim-vs-a2a-v2
    excludes: [default]

tasks:
  default:
    cmd: task -l